name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run a command remotely
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          commands: |
            cd echomskpodcast
            git reset --hard HEAD
            git pull origin main
            npm install
            git add --all
            git commit -m 'npm instal'
            git push origin main
